version: "3.1"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./bancodedados:/var/lib/postgresql/data
