-- AlterTable
ALTER TABLE "curriculos" ALTER COLUMN "telefone" DROP NOT NULL,
ALTER COLUMN "perfilLinkedIn" DROP NOT NULL,
ALTER COLUMN "cidade" DROP NOT NULL,
ALTER COLUMN "areaAtuacao" DROP NOT NULL;
